name: "Hello world2"
description: "My first real add-on!"
version: "1.0.1"
slug: "hello_world2"
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
startup: system
host_ipc: true
host_dbus: true
host_pid: true
privileged: ['NET_ADMIN','SYS_ADMIN', 'SYS_RESOURCE', 'IPC_LOCK', 'SYS_MODULE']
full_access: true
host_network: true
options:
  var1: asdfasdf
schema:
  var1: str