name: "Hello world2"
description: "My first real add-on!"
version: "1.0.1"
slug: "hello_world2"
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
boot: auto
host_network: true
apparmor: false
host_dbus: true
full_access: true
privileged:
- NET_ADMIN
- SYS_ADMIN
- SYS_RESOURCE
- IPC_LOCK
- SYS_MODULE
- SYS_RAWIO
- SYS_TIME
- SYS_NICE
devices:
- "/dev/mem:/dev/mem:rwm"
map:
- config:rw
- ssl:rw
- addons:rw
- share:rw
- backup:rw
host_ipc: true
host_pid: true
options:
  var1: asdfasdf
schema:
  var1: str