name: "Hello world2"
description: "My first real add-on!"
version: "1.0.1"
slug: "hello_world2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: auto
startup: system
privileged: ['NET_ADMIN','SYS_ADMIN']
full_access: true
host_network: true
options:
  var1: asdfasdf
schema:
  var1: str